<?php

namespace AppBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleCommentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
