<?php

namespace AppBundle\Repository;

/**
 * ArticleLikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleLikeRepository extends \Doctrine\ORM\EntityRepository
{
}
